version: '3.1'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rasplus
    volumes:
      - mysql-data:/data/db
    networks:
      - mynetwork

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: raspay
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
        - "6379:6379"
    networks:
        - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  mongo-data: